### ISSUE TITLE
Update to latest commit of bobpace/react-router branch

### ISSUE THREAD

**Issue by eriknyk** [nicolashery/example-isomorphic-one#1]
Hi,
Actually npm install fails

I see on you package.json you have

```
"react-router": "bobpace/react-router#2abe727231bf6e290e1e6fee9413426d94ceaaff",
```

that version of "react-router" doesn't exists any more,..
I've tried change it to:

```
"react-router": "0.12.0",
```

it seems works,.. but not at all,..
because routing is not working as expected,..

please can be update you example?
I've found that is very helpful

Best Regards.

**Comment by nicolashery** [comment]
Ah yes, I see what's going on. I'm using @bobpace's branch because I need the transition context (see https://github.com/rackt/react-router/pull/590, surprised it still hasn't been merged), but looks like the latest push rewrote history.. :( 

I'll update to the latest `bobpace/react-router` commit, but that also means updating to `react 0.13` and `fluxible 0.4`. Will try to get to it asap.

**Comment by bobpace** [comment]
Sorry for the breaking changes, but to avoid a stream of noise commits while keeping the pull request up to date I force push each time it needs to be updated.  (reference: http://stackoverflow.com/questions/7947322/preferred-github-workflow-for-updating-a-pull-request-after-code-review) I wasn't intending for it to become as long lived as it has for others to take a dependency on it.

**Comment by eriknyk** [comment]
thanks a lot for your soon response,

Best Regards.

**Comment by nicolashery** [comment]
It's a little trickier than I thought. Both React Router 0.13 and Fluxible 0.4 moved to using React's `context` (still undocumented I think), and I'm having trouble wrapping my head around it (although this has been useful: https://github.com/yahoo/flux-examples/tree/master/react-router).

Pinging https://github.com/yahoo/flux-examples/issues/116 also, since I'm using "transition context" in my [AuthMixin](https://github.com/nicolashery/example-isomorphic-one/blob/master/src/utils/AuthMixin.js) here (although should probably convert it to a higher-order component, since that seems to be the trend?).

**Comment by nicolashery** [comment]
Current progress so far: https://github.com/nicolashery/example-isomorphic-one/pull/2

Still not working though... :(

**Comment by eriknyk** [comment]
I get this error with webpack.

ERROR in ./~/react-router/modules/components/NotFoundRoute.js
Module parse failed: /Users/erik/towbook/towbook-foundation/node_modules/react-router/modules/components/NotFoundRoute.js Line 12: Unexpected reserved word
You may need an appropriate loader to handle this file type.
|  \* route hierarchy.
|  /
| class NotFoundRoute extends Route {}
|
| // TODO: Include these in the above class definition
 @ ./~/react-router/modules/index.js 3:24-61

---

with trying the latest tag 0.13.2 of react-router with the changes manually of the @bobpace PR https://github.com/rackt/react-router/pull/590

**Comment by nicolashery** [comment]
@eriknyk Ah yes, react-router is written in ES6 so need to build it to use it off of a GitHub repo. I just forked it and updated my PR to point to the correct commit (https://github.com/nicolashery/react-router/commit/2e375e94033e1cab5ed5b922395a79e368bb1929).

@bobpace Btw, no problem for the breaking change, I completely understand! That is the risk of using a branch, and not an official tag.. I just forked your version and am using that, which is what I should've done in the first place.. :)

**Comment by nicolashery** [comment]
@eriknyk should be all fixed on `master` now :) (don't forget to `npm install`)

Fixed in https://github.com/nicolashery/example-isomorphic-one/pull/2

**Comment by eriknyk** [comment]
I will try it, thanks @nicolashery 
probably the next thing to think and try how to implement this your same app,
to a ES6 React impl. where mixins are not exists any more.

this is a good explanation why. http://www.ian-thomas.net/managing-context-in-a-fluxible-app-using-react-router/

Best Regards.
